FROM python:3.9-slim

RUN pip install mlflow

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "/opt/airflow/mlruns", "--default-artifact-root", "/opt/airflow/mlruns", "--host", "0.0.0.0"]